### PR TITLE
Compiling on arm64

### PR DESCRIPTION
**Pull request by siranipour**

### CODE REVIEW

**Comment by Zaharid** [comment]
Do we need the gnuconfig dependency for every case?

**Comment by siranipour** [comment]
I believe so, I got that from the [conda-forge instructions](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/) which says to add the `gnuconfig` dependency for every auto tools recipe

**Comment by siranipour** [comment]
Is there any way to get the tests to run properly? Possibly by merging this into a branch in your repository? I believe they fail currently because I've not set up the ssh keys

**Comment by Zaharid** [comment]
Let's see.

**Comment by siranipour** [comment]
Ok it seems that they fail, possibly because the Macos latest is 10.15 as specified [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and we are using the 11.0 SDK?

Not too sure how we can get around this problem if this is the source of the error

**Comment by Zaharid** [comment]
No idea. I don't see an error message from which to start looking...

**Pull request merged**
